sjusite/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

sjusite/config/urls.py
from django.contrib import admin
from django.urls import path, include
from sju import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sju/', include('sju.urls')),
    path('common/', include('common.urls')),
]

sjusite/sju/urls.py
from django.urls import path
from . import views

# from django.conf import settings
# from django.conf.urls.static import static
app_name = 'sju'

urlpatterns = [
    path('', views.index, name='index'),
    
    path('semester/create/', views.semester_create, name="semester_create"),
    path('subject/create/<int:sem_id>', views.subject_create, name='subject_create'),
    
    path('read/<int:sem_id>/', views.read, name='read'),
    
    path('semester/update/<int:sem_id>/', views.semester_update, name='semester_update'),
    path('subject/update/<int:sub_id>/', views.subject_update, name='subject_update'),
    
    path('semester/delete/<int:sem_id>/', views.semester_delete, name='semester_delete'),
    path('subject/delete/<int:sub_id>', views.subject_delete, name='subject_delete'),
]

sjusite/sju/models.py
from django.db import models

# Create your models here.
class Semester(models.Model):
    table = models.CharField(max_length=200)                                # 시간표 이름
    credits = models.IntegerField(default=0)                                         # 이수 단위
    grade = models.FloatField(default=0.00)                                             # 학점 평점
    create_at = models.DateTimeField()                                      # create 시간
    update_at = models.DateTimeField(null=True, blank=True)                 # update 시간
    
    
    def __str__(self):
        return self.table

class Subjects(models.Model):
    semester = models.ForeignKey(Semester, on_delete=models.CASCADE)        # 과목에 연결할 semester model
    name = models.CharField(max_length=200)                                 # 과목 이름
    credit = models.IntegerField(default=0)                                          # 과목의 이수 인정 학점
    create_at = models.DateTimeField()                                      # create 시간
    update_at = models.DateTimeField(null=True, blank=True)                 # update 시간

sjusite/common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserForm(UserCreationForm):
    email = forms.EmailField(label='이메일')
    name = forms.CharField(max_length=200, label='이름')
    
    class Meta:
        model = User
        fields = ("username", "name", "password1", "password2", 'email')

sjusite/sju/forms.py
from django import forms
from sju.models import Semester, Subjects

class SemesterForm(forms.ModelForm):
    class Meta:
        model = Semester
        fields = ['table', 'credits', 'grade']
        widgets = {
            'table': forms.TextInput(attrs={'class': 'form-control'}),
            'credits': forms.TextInput(attrs={'class': 'form-control'}),
            'grade': forms.TextInput(attrs={'class': 'form-control'}),
        }
        lables = {
            'table': '시간표',
            'credits': '이수 학점',
            'grade' : '학점 평점',
        }

class SubjectsForm(forms.ModelForm):
    class Meta:
        model = Subjects
        fields = ['name', 'credit']
        labels = {
            'name': '과목 이름',
            'credit': '이수 학점',
        }

sjusite/common/views.py
from django.shortcuts import render, redirect
from django.contrib. auth import authenticate, login
from common.forms import UserForm

def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            
            login(request, user)
            return redirect('/sju/')
        
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

sjusite/sju/views.py
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from django.http import HttpResponseNotAllowed
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages
from .models import Semester, Subjects
from .forms import SemesterForm, SubjectsForm

def index(request):
    semester_list= Semester.objects.order_by('table')
    context = {'semester_list': semester_list}
    return render(request, 'sju/main_page.html', context)

def semester_create(request):
    
    if request.method == 'POST':
        form = SemesterForm(request.POST)
        if form.is_valid():
            sem = form.save(commit=False)
            sem.create_at = timezone.now()
            sem.save()
            return redirect('sju:index') 
    else:
        form = SemesterForm()
    context = {'form': form}
    return render(request, 'sju/semester_form.html', context)

def subject_create(request, sem_id):
    sem = get_object_or_404(Semester, pk=sem_id)
    
    if request.method == "POST":
        form = SubjectsForm(request.POST)
        if form.is_valid():
            sub = form.save(commit=False)
            sub.create_at = timezone.now()
            sub.semester = sem
            sub.save()
            # if result:
            #     semester.credits += subjects.credit
            #     semester.save()
            
            return redirect('sju:read', sem_id=sem.id)
    else:
        form = SubjectsForm()
    context = {'semester': sem, 'form': form}
    return render(request, 'sju/subjects_form.html', context)

def read(request, sem_id):
    sem = get_object_or_404(Semester, pk=sem_id)
    context = {'sem': sem}
    return render(request, 'sju/semester_read.html', context)
    
    
    # global semesters
    # article = ''
    # for semester in semesters:
    #     if semester['id'] == int(id):
    #         article = f'<h2>{semester["title"]}</h2>{semester["body"]}'
    #         break
        
    # return HttpResponse(baseHTML(article, id))

def semester_update(request, sem_id):
    sem = get_object_or_404(Semester, pk=sem_id)
    
    if request.method == "POST":
        form = SemesterForm(request.POST, instance=sem)
        if form.is_valid():
            sem = form.save(commit=False)
            sem.update_at = timezone.now()
            sem.save()
            return redirect('sju:read', sem_id = sem.id)
    else:
        form = SemesterForm(instance=sem)
    context = {'form': form}
    return render(request, 'sju/semester_form.html', context)

def subject_update(request, sub_id):
    sub = get_object_or_404(Subjects, pk=sub_id)
    
    if request.method == "POST":
        form = SubjectsForm(request.POST, instance=sub)
        if form.is_valid():
            sub = form.save(commit=False)
            sub.update_at = timezone.now()
            sub.save()
            return redirect('sju:read', sem_id=sub.semester.id)
    else:
        form = SubjectsForm(instance=sub)
    context = {'subjects': sub, 'form': form}
    return render(request, 'sju/subjects_form.html', context)

def semester_delete(request, sem_id):
    sem = get_object_or_404(Semester, pk=sem_id)
    
    sem.delete()
    return redirect('sju:index')

def subject_delete(request, sub_id):
    sub = get_object_or_404(Subjects, pk=sub_id)
    
    sub.delete()
    return redirect('sju:read', sem_id=sub.semester.id)

sjusite/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django CRUD</title>
</head>
<body>
    {% include 'navbar.html'%}

    {% block content %}
    {% endblock %}
</body>
</html>

sjusite/templates/common/login.html
{% extends 'base.html' %}
{% block content %}
<div>
    <form action="{% url 'common:login' %}" method="post">
        {% csrf_token %}
        <div>
            <label for="username">사용자ID</label>
            <input type="text" name="username" id="username"
                    value="{{form.username.value|default_if_none:''}}" placeholder="User name">
        </div>
        <div>
            <label for="password">비밀번호</label>
            <input type="password" name="password" id="password"
                    value="{{form.password.value|default_if_none:''}}" placeholder="Password">
        </div>
        <button type="submit">로그인</button>
    </form>
</div>
{% endblock %}

sjusite/templates/common/signup.html
{% extends "base.html" %}
{% block content %}
<div>
    <form action="{% url 'common:signup' %}" method="post">
        {% csrf_token %}
        
        <div>
            <label for="username">아이디</label>
            <input type="text" name="username" id="username"
                value="{{form.username.value|default_if_none:''}}">
        </div>
        <div>
            <label for="name">이름</label>
            <input type="text" name="name" id="name"
                value="{{form.name.value|default_if_none:''}}">
        </div>
        <div>
            <label for="password1">비밀번호</label>
            <input type="password" name="password1" id="password1"
                value="{{form.password1.value|default_if_none:''}}">
        </div>
        <div>
            <label for="password2">비밀번호 확인</label>
            <input type="password" name="password2" id="password2"
                value="{{form.password2.value|default_if_none:''}}">
        </div>
        <div>
            <label for="email">이메일</label>
            <input type="text" name="email" id="email"
                value="{{form.email.value|default_if_none:''}}">
        </div>
        <button type="submit">회원가입</button>
    </form>
</div>
{% endblock %}

sjusite/templates/form_error.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

sjusite/templates/navbar.html
<h1><a href="{% url 'sju:index' %}">나는 무슨 수업을 들었는가</a></h1>
<div>
    <ul>
        <li>
        {% if user.is_authenticated %}
        <a href="{% url 'common:logout' %}">{{ user.name }} (로그아웃)</a>
        {% else %}
        <a href="{% url 'common:login' %}">로그인</a>
        <a href="{% url 'common:signup' %}">회원가입</a>
        {% endif %}
        </li>
    </ul>
</div>

sjusite/templates/sju/main_page.html
{% extends 'base.html' %}
{% block content %}
{% if semester_list %}
    <ul>
        {% for sem in semester_list %}
        <li>
            <a href="{% url 'sju:read' sem.id %}">{{sem.table}}</a>
            <a href="{% url 'sju:semester_delete' sem.id %}">삭제</a>
        </li>
        {% endfor %}
    </ul>
{% else %}
    <p>학교를 아직 안 다녔나보군요?</p>
{% endif %}
<a href="{% url 'sju:semester_create' %}" class="btn btn-primary">학기 추가등록</a>
{% endblock %}

sjusite/templates/sju/semester_form.html
{% extends 'base.html' %}
{% block content %}
<div>
    <h5>학기 등록</h5>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-primary">등록하기</button>
    </form>
</div>
{% endblock %}

sjusite/templates/sju/semester_list.html
{% extends 'base.html' %}
{% block content %}
{% if semester_list %}
    <ul>
        {% for sem in semester_list %}
        <li><a href="{% url 'sju:read' sem.id %}">{{sem.table}}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>학교를 아직 안 다녔나보군요?</p>
{% endif %}
<a href="{% url 'sju:semester_create' %}" class="btn btn-primary">학기 추가등록</a>
{% endblock %}

sjusite/templates/sju/semester_read.html
{% extends 'base.html' %}
{% block content %}
<h2>{{sem.table}}</h2>
<div>
    이수학점: {{sem.credits}}
</div>
<div>
    평점: {{sem.grade}}
</div>
<div>
        <a href="{% url 'sju:semester_update' sem.id %}">수정</a>
</div>
<h5>{{sem.subjects_set.count}}개의 과목을 들었습니다.</h5>
<div>
    <ul>
        {% for sub in sem.subjects_set.all %}
        <li>
            {{ sub.name }} ({{sub.credit}}학점)
            <a href="{% url 'sju:subject_update' sub.id %}">과목 수정</a>
            <a href="{% url 'sju:subject_delete' sub.id %}">삭제</a>
        </li>
        {% endfor %}
    </ul>
</div>

<div>
    <a href="{% url 'sju:subject_create' sem.id %}">과목 등록</a>
</div>
{% endblock %}

sjusite/templates/sju/subjects_form.html
{% extends 'base.html' %}
{% block content %}
<div>
    <h5>과목 등록</h5>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <p><input type="submit" value="등록하기"></p>
    </form>
</div>
{% endblock %}